DROP TABLE IF EXISTS EXPENSE; 
CREATE TABLE  (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0)NOT NULL PRIMARY KEY,
                        DESCRIPTION varchar(255) NOT NULL, createdAt DATE,addedAt DATE);
                        
/**
 * 
INSERT INTO CUSTOMERS (DATA) VALUES ('data0');

INSERT INTO CUSTOMERS(DATA) VALUES ('data1');

INSERT INTO CUSTOMERS(DATA) VALUES ('data2');

INSERT INTO CUSTOMERS(DATA) VALUES ('data3');
                        
                        **/