

- name: Create registry-storage pvc
  tags: registry
  k8s:
    state: present
    kubeconfig: "{{kubeconfig}}"
    validate_certs: no
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ocs4registry
        namespace: openshift-image-registry
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
      wait: true
      wait_timeout: 180

- name: Add pvc registry-storage to image registry and expose it
  tags: registry
  k8s:
    state: present
    kubeconfig: "{{kubeconfig}}"
    validate_certs: no
    merge_type: merge
    definition:
      kind: Config
      apiVersion: imageregistry.operator.openshift.io/v1
      metadata:
        name: cluster
      spec:
        managementState: Managed
        storage:
          pvc:
            claim: ocs4registry
        defaultRoute: true
# Needs retry because Operator needs time to create that object
  failed_when: false
  register: patch_status
  retries: 18
  delay: 10
  until: patch_status.msg is not defined
