== Modernize legacy application


=== Enterprise Service Bus monolith

Companies are facing a problem with modern technology adoption and need to integrate old legacy application which they are
struggle maintain and that they have to support in the lifetime from 5-10 years.
Lot of this legacy applications are using SOAP as a integration protocol , SAML as security protocol and runnning on monolyth ESB system.
Usually ESB is a Top-Down approach there following  ascpect of services are centrilized:

* SOA governance / Endpoint definitions
* Routing
* Protocol transformation
* Mapping
* Content Enrichment and Mapping
* Security


lets see how we can address this with  Microservice Architecture and Red Hat Integration Bundle.


=== SOA governance / Endpoint definitions

Legasy application are using a WSDL (Web Services Description Language ) to describe Web services based on an abstract model of what the service offers.

TODO: ... add modern way...


=== Routing

Different clients are need different data and microservices are fine-grained APIs which means client need to interact
with multiple service. Solution for this will be to have API gateway that is the single entry point for all clients.

3scale API Gateway is the RedHat answer for microservices routing.

Useful links:
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.6/html/administering_the_api_gateway/operating-apicast


TODO: add example


=== Protocol transformation

Example of SOAP protocol transformation

https://github.com/nmajorov/fuse_eap_keycloak

**WSDL to Rest Migration Tool** helped to migrate from legacy service definitions.

More infos can be found here:
https://github.com/jboss-fuse/wsdl2rest
